//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Application
{
	public class TwentyGrid
	{
		private Array boxes;
		public TwentyGrid ()
		{
			boxes = Array.CreateInstance( typeof(int), 16 );
		}
		public void setColumn (int col, Array vals)
		{
			for (int row = 0; row < 4; row++) {
				boxes.SetValue(vals.GetValue(row), row * 4 + col);
			}
		}
		public Array getColumn (int col)
		{
			Array res = Array.CreateInstance (typeof(int), 4);
			for (int row = 0; row < 4; row++) {
				res.SetValue(boxes.GetValue(row * 4 + col), row);
			}
			return res;
		}
		public void setRow (int row, Array vals)
		{
			vals.CopyTo (boxes, row * 4);
		}
		public Array getRow (int row)
		{
			Array res = Array.CreateInstance (typeof(int), 4);
			for (int col = 0; col < 4; col++) {
				res.SetValue(boxes.GetValue(row * 4 + col), col);
			}
			return res;
		}
		public bool setEmpty (int val, int start)
		{
			for (int index = 0; index < 16; index++)
			{
				int randomIndex = (index + start) % 16;
				if ((int) boxes.GetValue (randomIndex) == 0)
				{
					boxes.SetValue (val, randomIndex);
					return true;
				}
			}
			return false;
		}
	}
}

